#!/bin/bash

NET1=192.168.2.0/24
IF1=enp0s3
IP1=192.168.2.2
T1=T1
GW1=192.168.2.1

NET2=192.168.3.0/24
IF2=enp0s8
IP2=192.168.3.2
T2=T2
GW2=192.168.3.1

filename='pesos.txt'
while read line; do
eval export "$line"
done < $filename

PROB1=$(echo "scale=2; $ISP1 / ($ISP1 + $ISP2)" | bc)
PROB2=$(echo "scale=2; 1 - $PROB1" | bc)


ip route del default
ip rule add fwmark 3 table $T1 prio 33000
ip rule add fwmark 4 table $T2 prio 33000

ip route del $NET1 dev $IF1 src $IP1 table $T1
ip route del default via $GW1 table $T1
ip route del $NET2 dev $IF2 src $IP2 table $T2
ip route del default via $GW2 table $T2
ip route add $NET1 dev $IF1 src $IP1 table $T1
ip route add default via $GW1 table $T1
ip route add $NET2 dev $IF2 src $IP2 table $T2
ip route add default via $GW2 table $T2

iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t mangle -F

iptables -t mangle -A PREROUTING -j CONNMARK --restore-mark
iptables -t mangle -A PREROUTING -m mark ! --mark 0 -j ACCEPT
iptables -t mangle -A PREROUTING -j MARK --set-mark 3
iptables -t mangle -A PREROUTING -m statistic --mode random --probability $PROB2 -j MARK --set-mark 4
iptables -t mangle -A PREROUTING -j CONNMARK --save-mark

echo "1" > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -j MASQUERADE
